# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  todoswebapi:
    image: todoswebapi
    build:
      context: .
      dockerfile: Todos.WebAPI/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5002:5002
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
